# Generated by Django 5.2 on 2025-04-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_remove_card_company_remove_card_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
