# Generated by Django 5.2 on 2025-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0005_card_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['column', 'order', 'created_at']},
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
